### ISSUE TITLE
OnlyOffice stops saving the update of document back to NextCloud

### ISSUE THREAD

**Issue by kraisit** [ONLYOFFICE/docker-onlyoffice-owncloud#12]
Problem: OnlyOffice does not save the update of document back to NextCloud.
The update content of document are still in OnlyOffice. When open the document again the update contents are in OnlyOffice Editor.

Please kindly help on this problem. In case of any configs, logs or info required, please feel free to let me know.

**Comment by alexanderonlyoffice** [comment]
Hello @kraisit,

Could you please send the screenshot of the ONLYOFFICE address settings in NextCloud administrator section.

**Comment by kraisit** [comment]
Dear @alexanderonlyoffice 

Please attached the screenshot of the ONLYOFFICE address setting.

![captured by explain and send screenshots](https://user-images.githubusercontent.com/23413150/33885835-1db84e50-df77-11e7-896b-347c4f05fc26.jpg)

My server is configured Ngnix with SSL so the Server address for internal requests from the Document Editing Service is set as https://nginx-server/. Attached here with nginx.conf for your information.
[nginx.zip](https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud/files/1551660/nginx.zip)

And example file that save from OnlyOffice Editor (File Name: TestFile.SaveFromOnlyOffice.docx) and download from NextCloud (File Name: TestFile.DownloadFromNextCloud.docx).

[TestFile.SaveFromOnlyOffice.docx](https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud/files/1551640/TestFile.SaveFromOnlyOffice.docx)
[TestFile.DownloadFromNextCloud.docx](https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud/files/1551641/TestFile.DownloadFromNextCloud.docx)

Notice that file download from NextCloud is empty while the one saved from OnlyOfficeEditor contains Hello World! Text.

Please kindly help on this.

Best Regards
Kraisit V.

**Comment by kraisit** [comment]
Dear @alexanderonlyoffice

Today I retry the setup with minimal configuration as describe in README.md and found the same issue as my previous post.

Attached here with the ONLYOFFICE settings and example files.

![screenshot of admin - nextcloud](https://user-images.githubusercontent.com/23413150/34317551-0dee7042-e7e4-11e7-8fb9-1fb291d69e75.jpg)

[TestFile.DownloadFromNextCloud.docx](https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud/files/1583914/TestFile.DownloadFromNextCloud.docx)
[TestFile.SaveFromOnlyOffice.docx](https://github.com/ONLYOFFICE/docker-onlyoffice-owncloud/files/1583915/TestFile.SaveFromOnlyOffice.docx)

Do you have any comments or suggestions on this?

Thank you and Best Regards,
Kraisit V.

**Comment by alexanderonlyoffice** [comment]
Hello @kraisit,

The addresses of ONLYOFFICE document server are incorrect in your settings. In the first field Document Editing Service should be specified the domain name or ip address of the server and then ds-vpath (example: https://**your-document-server-address**/ds-vpath/). If your document server is accessible from the public, there is no need ti use internal addresses of the advanced settings. But if you use internal URL addresses, there also should be the domain name or ip address of your document server in the second field.

Domain name or ip address of NextCloud should be also specified the domain name or ip address of your NextCloud server.

Check the accessibility of the document server from the server where your NextCloud is installed and vice versa using wget command in terminal (example: `wget https://document-server-address/`)

**Comment by kraisit** [comment]
Dear @alexanderonlyoffice 

Thank you very much. And appreciated on your help. You are right. After I update the first field "Document Editing Service" with domain name of the server and then ds-vpath, OnlyOffice can save document to nextcloud successfully.

Merry X'mas and Happy new year
Kraisit V.

**Comment by robin-thoni** [comment]
Sorry to dig into this issue, but I had the same problem, which was fixed by setting the full URL in `Document Editing Service address`. However, I don't understand why it is required: my understanding of those settings is that `Document Editing Service address` (`DocumentServerUrl`) will *only* be used by clients, `Document Editing Service address for internal requests from the server` (`DocumentServerInternalUrl`) will *only* be used internally by Nextcloud to talk to OnlyOffice, and `Server address for internal requests from the Document Editing Service` (`StorageUrl`) will *only* be used internally by OnlyOffice to talk to Nextcloud.

![image](https://user-images.githubusercontent.com/9640353/64065474-03f88700-cc06-11e9-804d-616926c7e43c.png)


Starting from this assumptions, `Document Editing Service address` should be able to be a simple absolute or even relative path:

![image](https://user-images.githubusercontent.com/9640353/64065501-3609e900-cc06-11e9-83a9-a2160d611fdf.png)

Sounds like I'm not the only one to understand those options this way, so why is it not working like this? Did I/we miss some doc?
